#!/bin/sh

# Stage and commit changes
git add -A && git commit

# Make sure all changes are applied
git diff --exit-code --quiet ||
    git diff --cached --exit-code --quiet ||
    exit 1

# Push changes to server while we rebuild the system, reporting success
git push --quiet &> /dev/null && (
    echo &&
    echo "=================" &&
    echo " PUSH SUCCEEDED! " &&
    echo "=================" ) || (
    echo &&
    echo "==============" &&
    echo " PUSH FAILED! " &&
    echo "==============" ) & 

# Rebuild system
sudo rsync -ah --delete /home/jadelynnmasker/nixos/ /etc/nixos/ &&
sudo nixos-rebuild switch

# Make sure push finishes
fg &> /dev/null